import { Route } from '../entities/route.entity';

// @ts-ignore
const routes: Route[] = [
  {
    id: 1,
    isActive: 1,
    name: 'Dashboard',
    fatherID: null,
    level: 1,
    url: '/',
    icon: 'mdi-home',
  },
  {
    id: 2,
    isActive: 1,
    name: 'Personas',
    fatherID: null,
    level: 2,
    url: '/people',
    icon: 'mdi-account-multiple',
  },
  {
    id: 3,
    isActive: 1,
    name: 'votar',
    fatherID: null,
    level: 3,
    url: '/votar',
    icon: 'mdi-handshake',
  },
  {
    id: 4,
    isActive: 1,
    name: 'Usuarios',
    fatherID: null,
    level: 4,
    url: '/usuarios',
    icon: 'mdi-account-circle',
  },
  {
    id: 5,
    isActive: 1,
    name: 'Mexico',
    fatherID: null,
    level: 5,
    url: '',
    icon: 'mdi-mexico',
  },
  {
    id: 6,
    isActive: 1,
    name: 'Estados',
    fatherID: 5,
    level: 6,
    url: '/estados',
    icon: 'mdi-badge-account-horizontal',
  },
  {
    id: 7,
    isActive: 1,
    name: 'Municipios',
    fatherID: 5,
    level: 7,
    url: '/municipality',
    icon: 'mdi-account-details',
  },
  {
    id: 8,
    isActive: 1,
    name: 'Zonas',
    fatherID: 5,
    level: 8,
    url: '/zonas',
    icon: 'mdi-google-maps',
  },
  {
    id: 9,
    isActive: 1,
    name: 'Secciones',
    fatherID: 5,
    level: 9,
    url: '/secciones',
    icon: 'mdi-vector-intersection',
  },
  {
    id: 10,
    isActive: 1,
    name: 'Configuracion',
    fatherID: null,
    level: 10,
    url: '',
    icon: 'mdi-cog-outline',
  },
  {
    id: 11,
    isActive: 1,
    name: 'Roles',
    fatherID: 10,
    level: 11,
    url: '/roles',
    icon: 'mdi-axis-arrow-lock',
  },
] as Route[];
export default routes;
